<a href="https://colab.research.google.com/github/Matinsalami/DataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to use Numpy

In [ ]:
import numpy as np
#we can directly make a list in python and turn it into an array in numpy
my_list = [1,2,3]
my_list = np.array(my_list)

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix = np.array(my_matrix)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#linspace
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [ ]:
#eye(identity matrix)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Random numbers
np.random.rand(5,5)

array([[0.08457713, 0.68003575, 0.88556741, 0.57909736, 0.91977192],
       [0.10998079, 0.72431431, 0.66767087, 0.37369514, 0.64799987],
       [0.95501948, 0.93178252, 0.19333365, 0.95135844, 0.47942711],
       [0.38774642, 0.68074137, 0.40998105, 0.10256768, 0.24068604],
       [0.10969909, 0.25996688, 0.1976483 , 0.88809599, 0.5333305 ]])

In [ ]:
np.random.rand(5)

array([0.16812997, 0.35781138, 0.67603469, 0.34040145, 0.0640146 ])

In [ ]:
#random from a standard distribution
np.random.randn(10)

array([-1.06285531,  0.36366404,  0.60831446, -0.76977094, -0.1208833 ,
       -0.31889424,  0.57690009, -1.35000526,  0.21062325, -1.01182681])

In [ ]:
#random integers between two values
np.random.randint(0,100,10)

array([21, 92, 77, 67, 91, 73, 82, 10, 26, 80])

## Following contains attributes and methods for an array

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
#reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#min,max,argmax(index of the largest value in the array),argmin
ranarr.max()

49

In [ ]:
ranarr.min()

17

In [ ]:
ranarr.argmin()

9

In [ ]:
ranarr.argmax()

1

In [ ]:
#shape
arr.shape

(25,)

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
#type of the array(float, int, string)
arr.dtype

dtype('int64')

## Numpy indexing and selection

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting

In [ ]:
#This is an option which is not present in python lists
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[:] = 99

In [ ]:
#I can copy the array to save the original one
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

## Indexing a 2D array (matrices)

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Take the second column of the matrix
arr_2d[1][0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[2,:]

array([35, 40, 45])

## Fancy indexing

In [ ]:
matrix = np.zeros((10,10))
for i in range(0,10):
  matrix[i] = i


In [ ]:
## It can be in any order
matrix[[2,3,4,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
matrix > 4

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
matrix[1] > 1

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr = np.arange(0,21)
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Numpy operations

In [ ]:
arr = np.arange(0,10)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#For 0/0 we get nan instead of an error
arr / arr

<ipython-input-33-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#Also here we get infinity
1/arr

<ipython-input-34-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr **3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Numpy universal operations

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
np.min(arr)

0

In [ ]:
np.argmax(arr)

9

In [ ]:
np.log(arr)

<ipython-input-41-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])